### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by audriu**
Just tested with fresh ubuntu install

### CODE REVIEW

**Comment by rsglobal** [comment]
Hi,

Thanks for your feedback.
Does glodroid builds fine after that for you?

**Comment by audriu** [comment]
It does not unfortunately...
but `sudo: pip: command not found` otherwise. 
Please advice. And thanks for coming back to me.
I use fresh Ubuntu 20.04.1 install

**Comment by audriu** [comment]
this does not work for fresh installation. Instructions are broken. I don't know how to fix...

**Comment by rsglobal** [comment]
It would be awesome if you can attach build log, so we can elaborate the issue.

**Comment by audriu** [comment]
https://pastebin.com/MgHPrU0W I have put logs here. please have a look

**Comment by roman-kovalivskyi** [comment]
@audriu I had some similar issues with pip and python2, I've fixed it for myself it with downloading older version of script. Would you try the following commands?
```
curl https://bootstrap.pypa.io/2.6/get-pip.py --output get-pip.py
chmod +x get-pip.py
sudo ./get-pip.py
sudo pip2 install Mako
```

**Pull request closed without merging**
