### PR TITLE
Add mtools to necessary packages

### PR DESCRIPTION
**Pull request by Uclydde**

### CODE REVIEW

**Comment by rsglobal** [comment]
Hello,
Thank you for contribution.
Please add your SOB to the commit message.

**Comment by Uclydde** [comment]
> Please add your SOB to the commit message.
I have modified the commit as requested.

**Comment by rsglobal** [comment]
You should use your real name.

You can find contribution rules here:
https://www.kernel.org/doc/html/v5.6/process/submitting-patches.html#developer-s-certificate-of-origin-1-1

**Comment by Uclydde** [comment]
Okay, I have modified the commit message with my proper sign-off.

**Pull request merged**
